{
	"name": "Veterinaria",
	"version": "1.0.0",
	"summary": "Módulo base para gestión veterinaria",
	"category": "Tools",
	"author": "Felipe Reynoso",
	"website": "www.github.com/Felirey03/veterinariaOdoo",
	"license": "LGPL-3",
	"depends": ["base","product","mail", "account"],
	"data": [
        'data/demo_data.xml',
        'data/cron_data.xml',
        'security/ir.model.access.csv',
		'views/turno_views.xml',
		'views/mascota_views.xml',
		'views/historial_views.xml',
		'views/vacuna_views.xml',
		'views/veterinaria_menuitems.xml',
    ],
	"installable": True,
	"application": False,
}	
